### ISSUE TITLE
License of the repo

### ISSUE THREAD

**Issue by waldyrious** [cheat/cheatsheets#2]
In order to allow collaboration, this repository should have a license. As a content-based repo (containing text, rather than runnable software), I would suggest a license like CC-BY 4.0; that's what we're [adopting](https://github.com/tldr-pages/tldr/pull/3687) at tldr-pages.

**Comment by waldyrious** [comment]
For related discussion, see https://github.com/cheat/cheat/issues/261.

**Comment by chrisallenlane** [comment]
@waldyrious, thanks for reaching out to me, and thanks for the helpful discussion links.

In order to make the cheatsheets as "libre" as possible, I have licensed them under the CC0, effectively placing them into the public domain. Feel free to use them however you wish!

https://github.com/cheat/cheatsheets/blob/master/.github/LICENSE.txt
