### ISSUE TITLE
How to use fzf with cheat?

### ISSUE THREAD

**Issue by Acidham** [cheat/cheatsheets#20]
I added `export CHEAT_USE_FZF=true` to .zshrc but I am not sure how to use `cheat` with fzf. 
When using `cheat **` fzf is running fuzzy search in filesystem but not in cheats.

**Comment by chrisallenlane** [comment]
Hi, @Acidham 

This repository is for cheatsheets. The repository for the `cheat` executable is here:
https://github.com/cheat/cheat

I'm going to close this ticket, but feel free to re-open it there.

Regarding your question: I'm afraid I can't help you personally, because I have no meaningful `zsh` experience. If you open the ticket on the `cheat` repository, though, perhaps someone from the community will be able to help you.
