### ISSUE TITLE
cheatpath path is not unique

### ISSUE THREAD

**Issue by yzcj105** [cheat/cheatsheets#6]
If the files are put in ".cheat/" folder, there comes out the error. 
Maybe it's because of the "." wildcard.

**Comment by chrisallenlane** [comment]
This is the issue tracker cheatsheets, rather than the `cheat` executable. The latter is found here:
https://github.com/cheat/cheat/issues/

That said, this reminds me of an error that I fixed recently. Please upgrade to the newest version of `cheat` and let me know (on the other issue tracker) if the issue persists. Thanks.
